### ISSUE TITLE
Upgrade libheif to 1.18.0

### ISSUE THREAD

**Issue by nahn20** [catdad-experiments/heic-convert#41]
We're running into issues with HEIC's produced by iOS 18 failing to be processed by this library. I believe this issue is fixed in `libheif` 1.18.0 ([see relevant issue](https://github.com/strukturag/libheif/issues/1190)).

**Comment by Sully1570** [comment]
is this why I'm getting 
`Could not parse HEIF file Invalid input: Unspecified: Metadata not correctly assigned to image`

**Comment by Sully1570** [comment]
I found that installing the npm module libheif-js as a failover for heic-convert somehow fixed the issue.  I'm guessing it is because installing the libheif-js module updated the underlying libheif dependency to 1.18+.  Would love to know why it's fixed if anyone would like to comment

**Comment by wilsonwangdev** [comment]
> `heic-convert` uses `libheif-js` as a dependency (it's where a lot of the work happens). `libheif-js` receives regular updates, but ultimately `heic-convert` pulls in a version as `"libheif-js": "^1.17.1"`. This accepts any non-breaking changes -- and today, nothing inherently requires that `libheif-js` must be updated. If you `npm install heic-convert` today, you will get whatever the latest `libheif-js` is. This is pretty common and also central to how npm dependencies work.
> 
> In your existing projects (i.e. ones where you installed `heic-convert` a while ago), it is _you_ preventing updates through your package-lock file. So you can also update your project, through any means that causes your package-lock to update (e.g. remove and reinstall `heic-convert`, pin some dependency of `heic-convert` to your project, etc.)

My project is using heic-convert@1.2.4 (I checked it in my node_modules/heic-convert/package.json), if I want to tackle the iOS18 image convert problem, should I upgrade [libheif](https://github.com/strukturag/libheif) to v1.18.x separately or upgrade heic-convert to latest (2.1.0).

If the latter choice is suggested, how can I ensure there is no breaking changes of heic-convert. Because from 1.x.x to 2.x.x often means a major version upgrade with breaking changes. But I can't find what changes happened of this package. Could you please give me any advice? @catdad
